export const ROUTES = {
  REGISTER_ROUTE: "/register",
  LOGIN_ROUTE: "/login",
  DASHBOARD_ROUTE: "/articles",
  CATCH_ALL_ROUTE: "*",
  ARTICLES_FIRST_PAGE_PATH: "",
  ARTICLES_PAGE_PATH: "page/:page",
  CREATE_ARTICLE_PATH: "create",
  EDIT_ARTICLE_PATH: "edit/:slug",
};

export const ROUTE_NAMES = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  ARTICLES_FIRST_PAGE: "ARTICLES_FIRST_PAGE",
  ARTICLES_PAGE: "ARTICLES_PAGE",
  CREATE_ARTICLE: "CREATE_ARTICLE",
  EDIT_ARTICLE: "EDIT_ARTICLE",
};
